import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'

import { Container, Box, Typography, TextField, Button } from '@mui/material';

import { useState, useEffect } from 'react'
import { useRouter } from 'next/router'

var codec = require('json-url')('lzw');

export default function N() {
  let router = useRouter()

  const [values, setValues] = useState({
    source: '',
    medium: '',
    campaign: ''
  })
  const [link, setLink] = useState('')
  const [string, setString] = useState('')
  const [finalLink, setFinalLink] = useState('')

  function handleChange(e) {
    const value = e.target.value;
    setLink(value)
    setFinalLink(value + string)
  }

  function generateString() {
    let newString = '';
    // Loop the value object
    for (const [key, value] of Object.entries(values)) {
      // If this key has a value, add it to the string
      if (value) {
        // If we already have something in the string, seperate with &
        if (newString.length > 0) {
          newString = newString.concat("&")
        } else {
          newString = newString.concat("?")
        }
        newString = newString.concat("utm_" + key + "=" + value)
      }
    }
    setString(newString)
  }

  async function readParameters(query) {
    let q = await codec.decompress(query);
    setValues(q)
  }

  // Check if there's a URL parameter called "query" present
  function useQuery() {
    return new URLSearchParams(router.query);
  }

  let query = useQuery();
  let incomingQuery = query.get("q");

  // On first load, get the values from query parameter
  useEffect(() => {
    if (incomingQuery) {
      readParameters(incomingQuery)
    }
  }, [incomingQuery])

  // Each time the values object updates, generate a new string
  useEffect(() => {
    generateString()
  }, [values])

  return (
    <>
      <Head>
        <title>Generate UTM link from template</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Container>
        <Typography variant="h1">Generate UTM link from template</Typography>
        <TextField name="link" label="Paste your link here" variant="outlined" value={link} onChange={handleChange} />
        <Typography>{finalLink}</Typography>
        <Link href="/"><Button>Create your own template</Button></Link>
      </Container>
    </>
  )
}
