import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'

import { Container, Box, Typography, TextField, Button, Paper, Alert, AlertTitle, Grow } from '@mui/material';

import { useState, useEffect } from 'react'
import { useRouter } from 'next/router'
import {CopyToClipboard} from 'react-copy-to-clipboard';

var codec = require('json-url')('lzw');

export default function N() {
  let router = useRouter()

  const [values, setValues] = useState({
    source: '',
    medium: '',
    campaign: ''
  })
  const [link, setLink] = useState('')
  const [string, setString] = useState('')
  const [finalLink, setFinalLink] = useState('')
  const [copied, setCopied] = useState(false)

  function handleChange(e) {
    const value = e.target.value;
    setLink(value)
    setFinalLink(value + string)
  }

  function generateString() {
    let newString = '';
    // Loop the value object
    for (const [key, value] of Object.entries(values)) {
      // If this key has a value, add it to the string
      if (value) {
        // If we already have something in the string, seperate with &
        if (newString.length > 0) {
          newString = newString.concat("&")
        } else {
          newString = newString.concat("?")
        }
        newString = newString.concat("utm_" + key + "=" + value)
      }
    }
    setString(newString)
  }

  async function readParameters(query) {
    let q = await codec.decompress(query);
    setValues(q)
  }

  // Check if there's a URL parameter called "query" present
  function useQuery() {
    return new URLSearchParams(router.query);
  }

  let query = useQuery();
  let incomingQuery = query.get("q");

  // On first load, get the values from query parameter
  useEffect(() => {
    if (incomingQuery) {
      readParameters(incomingQuery)
    }
  }, [incomingQuery])

  // Each time the values object updates, generate a new string
  useEffect(() => {
    generateString()
  }, [values])

  return (
    <>
      <Head>
        <title>Generate UTM link from template</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Container>
        <Typography variant="h3">Generate UTM link from template</Typography>
        <Typography>Hey there! 👋</Typography>
        <Typography>So someone needs you to UTM tag a link and sent you here, huh?</Typography>
        <Typography>Don't worry, it's super simple! Just paste the link you want to use below and we'll give you a new link back with the UTM-parameters added, just like whoever sent you here wanted.</Typography>
        <Paper
          sx={{
            p: 4
          }}
        >
          <Typography>Step 1</Typography>
          <Typography>Paste your destination link here</Typography>
          <TextField fullWidth name="link" label="Paste your link here" variant="outlined" value={link} onChange={handleChange} />
        </Paper>
        <Grow in={finalLink}>
          <Paper
            sx={{
              p: 4,
              mt: 2
            }}
          >
            <Typography>Step 2</Typography>
            <Typography>Here is your tagged link! Use it just like you would a normal link.</Typography>
            <Alert
              severity="success"
              action={
                <CopyToClipboard
                  text={finalLink}
                  onCopy={() => setCopied(true)}
                >
                  <Button size="small" color="inherit">{copied ? "Copied!" : "Copy"}</Button>
                </CopyToClipboard>
              }
            >
              {finalLink}
            </Alert>
          </Paper>
        </Grow>
        <Link href="/"><Button>Create your own template</Button></Link>
      </Container>
    </>
  )
}
